# Generated by Django 6.1 on 2026-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='current_location_string',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='location_source',
            field=models.CharField(choices=[('gps', '🟢 Live GPS'), ('qr', '🔵 Faculty QR Scanner'), ('timetable', '🟡 Expected from Timetable'), ('report', '🟠 Student Reported')], default='timetable', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='location_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
