# Generated by Django 6.1 on 2026-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_qrlocation_facultyprofile_current_location_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
