"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from the .env file locally, or Render environments in production
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- SECURITY & ENVIRONMENT CONFIG ---

# Pull key safely from environment variable, fallback to development string only if empty
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-c(6yn11-t!z4w!(58m-3y=o+fzg6+zj-8q%3s9oe&0u-7w(-#e')

# Turns off debug mode automatically in production when DEBUG=False env is present
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allow Render/Railway cloud domains along with standard local hosts
ALLOWED_HOSTS = ['.render.com', '.railway.app', 'localhost', '127.0.0.1', '*']


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'faculty',
    'location',
    'community',
    'appointments',
    'campus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <-- CRITICAL: Serves static assets efficiently in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- AUTHENTICATION CONFIG ---

AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = 'faculty:search'
LOGOUT_REDIRECT_URL = 'faculty:search'


# --- DATABASE ---

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --- PASSWORD VALIDATION ---

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- INTERNATIONALIZATION ---

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES ASSETS (CSS, JavaScript, Images) ---

STATIC_URL = 'static/'

# CRITICAL FOR PRODUCTION DEPLOYMENT:
# Tells Django where to compile all UI asset layouts during Render build stage
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Enables aggressive file compression and caching behavior via WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- EMAIL BACKEND ---

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}